-- Day 8: EMI / Loan schedule + reminder tracking
-- Run in Supabase Dashboard -> SQL Editor -> New Query

create table if not exists public.loan_emis (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name varchar(120) not null,
  loan_type varchar(20) not null default 'emi' check (loan_type in ('emi','loan')),
  lender varchar(120),
  amount numeric(14,2) not null check (amount >= 1),
  start_date date not null,
  end_date date not null,
  due_day smallint not null check (due_day between 1 and 31),
  notes varchar(500),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint loan_emis_date_order check (end_date >= start_date)
);

create table if not exists public.emi_payments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  emi_id bigint not null references public.loan_emis(id) on delete cascade,
  due_date date not null,
  paid_at timestamptz not null default now(),
  note varchar(500),
  created_at timestamptz not null default now(),
  unique (emi_id, due_date)
);

create index if not exists loan_emis_user_dates_idx
  on public.loan_emis (user_id, start_date, end_date, is_active);

create index if not exists emi_payments_user_due_idx
  on public.emi_payments (user_id, due_date);

 drop trigger if exists trg_loan_emis_updated_at on public.loan_emis;
create trigger trg_loan_emis_updated_at
before update on public.loan_emis
for each row execute function public.set_updated_at();

alter table public.loan_emis enable row level security;
alter table public.emi_payments enable row level security;

drop policy if exists "loan_emis_select_own" on public.loan_emis;
drop policy if exists "loan_emis_insert_own" on public.loan_emis;
drop policy if exists "loan_emis_update_own" on public.loan_emis;
drop policy if exists "loan_emis_delete_own" on public.loan_emis;
create policy "loan_emis_select_own" on public.loan_emis for select to authenticated using (user_id = auth.uid());
create policy "loan_emis_insert_own" on public.loan_emis for insert to authenticated with check (user_id = auth.uid());
create policy "loan_emis_update_own" on public.loan_emis for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "loan_emis_delete_own" on public.loan_emis for delete to authenticated using (user_id = auth.uid());

drop policy if exists "emi_payments_select_own" on public.emi_payments;
drop policy if exists "emi_payments_insert_own" on public.emi_payments;
drop policy if exists "emi_payments_update_own" on public.emi_payments;
drop policy if exists "emi_payments_delete_own" on public.emi_payments;
create policy "emi_payments_select_own" on public.emi_payments for select to authenticated using (user_id = auth.uid());
create policy "emi_payments_insert_own" on public.emi_payments for insert to authenticated with check (user_id = auth.uid());
create policy "emi_payments_update_own" on public.emi_payments for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "emi_payments_delete_own" on public.emi_payments for delete to authenticated using (user_id = auth.uid());

grant select, insert, update, delete on public.loan_emis to authenticated;
grant select, insert, update, delete on public.emi_payments to authenticated;
grant usage, select on sequence public.loan_emis_id_seq to authenticated;
grant usage, select on sequence public.emi_payments_id_seq to authenticated;
